---
abstract: 'Plugin to verify pod coverage in our app routes.'
author:
  - 'Dinis Rebolo <drebolo@cpan.org>'
build_requires:
  Test::NoWarnings: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-RoutePodCoverage
requires:
  Dancer2: '0.14'
  Pod::Simple::Search: '3.28'
  Pod::Simple::SimpleTree: '3.28'
resources:
  bugtracker: https://github.com/drebolo/Dancer2-Plugin-RoutePodCoverage/issues
  repository: https://github.com/drebolo/Dancer2-Plugin-RoutePodCoverage
version: '0.07'
